"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio = [1, 3, 6]
show_hidden = true
sort_by = "alphabetical"
sort_dir_first = true
scrolloff = 5
title_format = "Yazi: {cwd}"

[preview]
wrap = "no"
tab_size = 2
max_width  = 2400
max_height = 2400
image_delay = 0

